# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 05:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serv', '0004_auto_20161219_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='key_model',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='keymodel',
            name='user',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClientModel',
        ),
    ]
