# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0005_auto_20161219_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymodel',
            name='user',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serv.UserDetailsModel'),
        ),
    ]
