# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0006_auto_20161220_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsmodel',
            name='key',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serv.KeyModel'),
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='user',
            field=models.OneToOneField(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serv.UserDetailsModel'),
        ),
    ]
