# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 03:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0007_auto_20161220_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymodel',
            name='user',
        ),
    ]
